# Generated by Django 4.1.2 on 2022-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='contents',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='page',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
