# Generated by Django 4.1.2 on 2022-11-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanxi_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(max_length=511, null=True),
        ),
    ]
