# Generated by Django 4.1.2 on 2022-11-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                default="https://img.dpm.org.cn/Uploads/Picture/2016/12/29/s5864b06921de3.png",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="introduction",
            field=models.CharField(default="请至淘宝查看详细介绍", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="product_url",
            field=models.CharField(
                default="https://space.bilibili.com/594844283?spm_id_from=333.337.0.0",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="产品大厅", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="未命名", max_length=50),
        ),
    ]
