# Generated by Django 4.1.2 on 2022-11-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('audio_path', models.CharField(max_length=255)),
                ('classification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialect_display.classification')),
            ],
            options={
                'db_table': 'audio',
            },
        ),
    ]
