# Generated by Django 4.1.2 on 2022-11-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialect_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
